djangoblog/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$',views.signup_view,name="signup"),
    re_path(r'^login/$',views.login_view,name="login"),
    re_path(r'^logout/$',views.logout_view,name="logout"),
]

djangoblog/articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$', views.article_list, name="list"),
    re_path(r'^create/$',views.article_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail"),
]

djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as articles_views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^about/$', views.about),
    re_path(r'^articles/',include('articles.urls')),
    re_path(r'^accounts/',include('accounts.urls')),
    re_path(r'^$', articles_views.article_list, name="home"),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangoblog/accounts/models.py
from django.db import models

# Create your models here.

djangoblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank = True)
    author = models.ForeignKey(User, default = None, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:30] + '...'

djangoblog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            #login
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

djangoblog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles': articles})

def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

djangoblog/djangoblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homePage')
    return render(request,'homepage.html')

def about(request):
    #return HttpResponse('about')
    return render(request,'about.html')

djangoblog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Logowanie</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Zaloguj">
  </form>
{% endblock %}

djangoblog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Rejestracja</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Zarejestruj">
  </form>
{% endblock %}

djangoblog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="create-article">
    <h2>Stwórz nowy artykuł</h2>
      <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Dodaj">
      </form>
  </div>
  <script src="/static/slugify.js" charset="utf-8"></script>
{% endblock %}

djangoblog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
      <p>{{article.date}}</p>
    <img src="{{article.thumb.url}}"/>
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    </div>
</div>
{% endblock %}

djangoblog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Lista artykułów</h1>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
          <p>{{article.snippet}}</p>
          <p>{{article.date}}</p>
          <p class="author">{{article.author.username}}</p>
        </div>
      {% endfor %}
    </div>
{% endblock %}

djangoblog/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>.Blog</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" width=300px style="margin-top:-40px"/></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" >Wyloguj</button>
            </form>
          </li>
          <li>
          <a href="{% url 'articles:create' %}" class="highlight">Dodaj artykuł</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login'%}" class="highlight">Zaloguj</a></li>
          <li><a href="{% url 'accounts:signup'%}" class="highlight">Dołącz</a></li>

          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>